### ISSUE TITLE
Fix unique generation of ActorNames

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/simona#103]
On very large datasets the current implementation of the actor naming uuid tends to be not unique anymore. Therefore we need to find an alternative for the unique name generation. 

**Possible approaches:**
- remove `substring(0,8)` (might clutter logs...)
- find another method to generate unique identifiers (maybe hash values?

**Affected line:**
![Clipboard - 19  Januar 2022 17_03](https://user-images.githubusercontent.com/42348110/150369010-83fff0f2-fd23-4ac6-841a-6325831c736d.png)

**Comment by t-ober** [comment]
The system participants are built with 

```
    def simonaActorOf(props: Props, actorId: String): ActorRef =
      refFactory.actorOf(props, actorName(props, actorId))
```

where the actorId is used. Find out what we want here.
