### ISSUE TITLE
Fix `genConfigSample` gradle task

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/simona#148]
Possible merge it with `genConfigClass`, since it requires parameter `--dd` for output anyway

**Comment by johanneshiry** [comment]
Don't get the rationale behind this. Would you mind explaining this a little bit more detailed. AFAIK `genConfigSample` and `genConfigClass` do totally different things? Is this a code cleanup proposal or a vote for removing `genConfigSample` in favor of `genConfigClass` (which IMHO doesn't make sense).

**Comment by sebastian-peter** [comment]
`genConfigClass` is broken in its current form, it throws a `FileNotFoundException`
