### ISSUE TITLE
Consider setting java version to 11

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/simona#15]
We currently depend on an outdated and possibly insecure version of jGraphT (1.4) as with jGraphT 1.5 java 11 is required. Therefore, as this should not change much, we should consider setting the projects java version from 1.8 to 11 

May be considered in conjunction with [PSDM#307](https://github.com/ie3-institute/PowerSystemDataModel/issues/307)

**Comment by sebastian-peter** [comment]
We switched to Java 17 now with  #60
