### ISSUE TITLE
Export uml diagrams as SVG instead of PNG

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/simona#156]
https://github.com/ie3-institute/simona/blob/6acd7d36a327253a4a32523c897c9f38736873b8/gradle/scripts/documentation.gradle#L53

Currently, we are exporting uml diagrams as png files. However, we might consider exporting them as SVG to get rid of binary files in the repository.

**Comment by danielfeismann** [comment]
Since the uml diagrams are integrated through plantuml-proxy with #220 we should decide to remove the puml2png-task from documentation.gradle or to keep it
