### ISSUE TITLE
Use correct tick when simulation ends

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/simona#159]
When the simulation ends, the current tick instead of the `endTick` should be used. This makes a difference if the simulation ends prematurely.

https://github.com/ie3-institute/simona/blob/17a915f279a5b7eecd46e42f87a968c0c2792946/src/main/scala/edu/ie3/simona/scheduler/SchedulerHelper.scala#L532

Finally, add a test for this.

**Comment by RishiKumarRay** [comment]
so we need to replace endTick with CurrentTick? or am i missing out something

**Comment by sebastian-peter** [comment]
Yes, the current tick is stored in `stateData.time.nowInTicks`.

The problem here is the test though, as we do not have any tests for SimScheduler and failed simulations in this repository yet. This could be a little tricky.

**Comment by sebastian-peter** [comment]
SimScheduler tests have been consolidated since #286, so this could be more doable now
