### ISSUE TITLE
Fix MavenCentral deployment credits

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/simona#16]
Jenkins complains about insecure string interpolation when deploying to maven central. While the credentials are masked and therefore this _should_ be safe to use, we should investigate another way to pass in the credentials there. 

Should be doable fast forward, as we use credentials beforehand already and therefore one may just apply the concept of an existing credentials implementation.

If you start working on this, feel free to contact me for details.

**Comment by sebastian-peter** [comment]
Resolved in #573
