### ISSUE TITLE
Missing implementation of evcs pricing

### ISSUE THREAD

**Issue by staudtMarius** [ie3-institute/simona#239]
The current dev branch of simona does not work with the MobilitySimulator because some classes needed for pricing informations of evcs are missing. These missing classes are currently only avaible in the branch mb/#42-ba-feature-branch.

**Comment by sebastian-peter** [comment]
Yes, this is part of #32, which has been further developed in #41. Merging all changes into dev while also conducting a proper review process will not be trivial here, so I suggest using #41 for co-simulations with MobilitySimulator still.

**Comment by sebastian-peter** [comment]
I just updated #41 to include the recent changes of dev

**Comment by sebastian-peter** [comment]
Currently not planned
