### ISSUE TITLE
Adjust reading of joint grid container to be able to parse hierarchic grid structures.

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/simona#478]
Depends on: https://github.com/ie3-institute/PowerSystemDataModel/pull/769

The `Gridprovider.gridFromConfig` method currently does not consider the `isHierarchic` parameters but just assumes a flat directory hierarchy. This should be changed, after the corresponding option is available in the PSDM

**Comment by jo-bao** [comment]
Solved with PSDM 4.0
