### ISSUE TITLE
Update rtd-template >1.2.0

### ISSUE THREAD

**Issue by danielfeismann** [ie3-institute/simona#505]
Currently references are not rendered correctly with rtd-template 1.2. Should be fixed with https://github.com/readthedocs/sphinx_rtd_theme/issues/1411 afterwards we can go to sphinx >6 and rtd-template >1.2.0

**Comment by sebastian-peter** [comment]
Could also be this issue? https://github.com/readthedocs/sphinx_rtd_theme/issues/1530
