### ISSUE TITLE
Simulation continues despite of exception

### ISSUE THREAD

**Issue by danielfeismann** [ie3-institute/simona#610]
[PSDM#886](https://github.com/ie3-institute/PowerSystemDataModel/issues/886) throws an exception but simulation does not stop

**Comment by sebastian-peter** [comment]
@danielfeismann Could you identify the actor that is calling the failing method in PSDM and thus should stop first?

**Comment by danielfeismann** [comment]
@sebastian-peter No. But I should have the config etc. so we could rerun simulation and evaluate the next days.
