### ISSUE TITLE
Introduce new scheduling protocol

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/simona#650]
The new scheduling protocol includes a bunch changes:
- activations are scheduled without trigger, there is only a simple activation with the current tick
- completions only include the ActorRef of the actor that is completed (no more trigger id) and possibly a new tick

**Comment by danielfeismann** [comment]
Some minor side whish that may could be added here: In all_tbw we actually have some fixed timeOut for SimScheduler which is hard coded to ten minutes which could/should be supported by config to make this adaptable.

**Comment by sebastian-peter** [comment]
@danielfeismann I believe that timeout was for debugging purposes anyways, since after that time passed, scheduler state was dumped

**Comment by danielfeismann** [comment]
@sebastian-peter True, this one only logs. I miss interpreted this. There is another timeout with the same duration...
