### ISSUE TITLE
Additional tests to check flexibility options of thermal house and storage

### ISSUE THREAD

**Issue by danielfeismann** [ie3-institute/simona#729]
- e.g. thermal house without storage
- ...

based on this comment:

     Should we also have tests for the other cases?

_Originally posted by @danielfeismann in https://github.com/ie3-institute/simona/pull/714#discussion_r1482582742_

**Comment by sebastian-peter** [comment]
Including more variations of house temperature and storage space. Currently, only `the house is heated up and storage has space` is tested
