### ISSUE TITLE
Consider scaling factor with flex options

### ISSUE THREAD

**Issue by sebastian-peter** [ie3-institute/simona#734]
Scaling is applied in `SystemParticipant.calculateApparentPower`, which is not utilized by participant models when calculating flex options and handling flex control.

**Comment by danielfeismann** [comment]
Oh yes, we missed that point. Would it be a possibility to scale within the flex messages?

**Comment by sebastian-peter** [comment]
> Oh yes, we missed that point. Would it be a possibility to scale within the flex messages?

That's what we should discuss...

**Comment by sebastian-peter** [comment]
Depends on #1012
