### ISSUE TITLE
Error handling for invalid time of primary data

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/simona#981]
Currently the simulation stalls when time field of primary data is outside of the range of simulation `startDate` and `endDate`.
We should throw an exception in these cases instead rather than leaving the user waiting and wondering / despairing.

The issue can be reproduced by running simona with vn_simona after setting `vn_simona.conf` to:

```
simona.time.startDateTime = "2012-01-01T00:00:00Z"
simona.time.endDateTime = "2012-01-01T02:00:00Z"
```

**Comment by sebastian-peter** [comment]
Per our discussion, we should also consider testing cases where timeseries range and simulation time range overlap partly. So in total that'd be:
- Not a single timeseries date in simulation time range
- Timeseries starts with a considerable delay after simulation start
- Timeseries ends with a considerable delay before simulation start

There should be tests for all of this.

**Comment by staudtMarius** [comment]
This problem occurres because of `ParticipantAgentFundamantals` (lines: 142 - 144). One possible fix is shown below.

current:
```java
senderToMaybeTick._2.foreach { tick =>
    scheduler ! Completion(self.toTyped, Some(tick))
}
```

fixed:
```java
scheduler ! Completion(self.toTyped, senderToMaybeTick._2)
```
